### ISSUE TITLE
Dependency: @Shared/utility/time is missing

### ISSUE THREAD

**Issue by ShakirPlayZ** [Stuyk/rebar-chat#1]
[plugin:vite:import-analysis] Failed to resolve import "@Shared/utility/time" from "../src/plugins/chat/webview/components/ChatMessage.vue". Does the file exist?
F:/rebar-altv/src/plugins/chat/webview/components/ChatMessage.vue:4:32
1  |  import { defineComponent as _defineComponent } from "vue";
2  |  import { computed } from "vue";
3  |  import { formatTimestamp } from "@Shared/utility/time";
   |                                   ^
4  |  import { ChatConfig } from "../../shared/config";
5  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
    at formatError (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:50830:46)
    at TransformContext.error (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:50824:19)
    at normalizeUrl (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:66128:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:66283:47
    at async Promise.all (index 2)
    at async TransformContext.transform (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:66204:13)
    at async Object.transform (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:51139:30)
    at async loadAndTransform (file:///F:/rebar-altv/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:53894:29
Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.ts.

**Comment by Stuyk** [comment]
Update Rebar.
